import { AvoOrHetArchief } from '../../shared/types';

import {
	DeleteContentBlockDocument as DeleteContentBlockDocumentAvo,
	DeleteContentBlockMutation as DeleteContentBlockMutationAvo,
	DeleteContentBlockMutationVariables as DeleteContentBlockMutationVariablesAvo,
	DeleteContentLabelLinksDocument as DeleteContentLabelLinksDocumentAvo,
	DeleteContentLabelLinksMutation as DeleteContentLabelLinksMutationAvo,
	DeleteContentLabelLinksMutationVariables as DeleteContentLabelLinksMutationVariablesAvo,
	GetContentByIdDocument as GetContentByIdDocumentAvo,
	GetContentByIdQuery as GetContentByIdQueryAvo,
	GetContentByIdQueryVariables as GetContentByIdQueryVariablesAvo,
	GetContentLabelsByContentTypeDocument as GetContentLabelsByContentTypeDocumentAvo,
	GetContentLabelsByContentTypeQuery as GetContentLabelsByContentTypeQueryAvo,
	GetContentLabelsByContentTypeQueryVariables as GetContentLabelsByContentTypeQueryVariablesAvo,
	GetContentPagesDocument as GetContentPagesDocumentAvo,
	GetContentPagesQuery as GetContentPagesQueryAvo,
	GetContentPagesQueryVariables as GetContentPagesQueryVariablesAvo,
	GetContentTypesDocument as GetContentTypesDocumentAvo,
	GetContentTypesQuery as GetContentTypesQueryAvo,
	GetContentTypesQueryVariables as GetContentTypesQueryVariablesAvo,
	GetPermissionsFromContentPageByPathDocument as GetPermissionsFromContentPageByPathDocumentAvo,
	GetPermissionsFromContentPageByPathQuery as GetPermissionsFromContentPageByPathQueryAvo,
	GetPermissionsFromContentPageByPathQueryVariables as GetPermissionsFromContentPageByPathQueryVariablesAvo,
	GetPublicContentPagesByTitleDocument as GetPublicContentPagesByTitleDocumentAvo,
	GetPublicContentPagesByTitleQuery as GetPublicContentPagesByTitleQueryAvo,
	GetPublicContentPagesByTitleQueryVariables as GetPublicContentPagesByTitleQueryVariablesAvo,
	GetPublicProjectContentPagesByTitleDocument as GetPublicProjectContentPagesByTitleDocumentAvo,
	GetPublicProjectContentPagesByTitleQuery as GetPublicProjectContentPagesByTitleQueryAvo,
	GetPublicProjectContentPagesByTitleQueryVariables as GetPublicProjectContentPagesByTitleQueryVariablesAvo,
	GetPublicProjectContentPagesDocument as GetPublicProjectContentPagesDocumentAvo,
	GetPublicProjectContentPagesQuery as GetPublicProjectContentPagesQueryAvo,
	GetPublicProjectContentPagesQueryVariables as GetPublicProjectContentPagesQueryVariablesAvo,
	InsertContentBlocksDocument as InsertContentBlocksDocumentAvo,
	InsertContentBlocksMutation as InsertContentBlocksMutationAvo,
	InsertContentBlocksMutationVariables as InsertContentBlocksMutationVariablesAvo,
	InsertContentDocument as InsertContentDocumentAvo,
	InsertContentLabelLinksDocument as InsertContentLabelLinksDocumentAvo,
	InsertContentLabelLinksMutation as InsertContentLabelLinksMutationAvo,
	InsertContentLabelLinksMutationVariables as InsertContentLabelLinksMutationVariablesAvo,
	InsertContentMutation as InsertContentMutationAvo,
	InsertContentMutationVariables as InsertContentMutationVariablesAvo,
	SoftDeleteContentDocument as SoftDeleteContentDocumentAvo,
	SoftDeleteContentMutation as SoftDeleteContentMutationAvo,
	SoftDeleteContentMutationVariables as SoftDeleteContentMutationVariablesAvo,
	UpdateContentBlockDocument as UpdateContentBlockDocumentAvo,
	UpdateContentBlockMutation as UpdateContentBlockMutationAvo,
	UpdateContentBlockMutationVariables as UpdateContentBlockMutationVariablesAvo,
	UpdateContentByIdDocument as UpdateContentByIdDocumentAvo,
	UpdateContentByIdMutation as UpdateContentByIdMutationAvo,
	UpdateContentByIdMutationVariables as UpdateContentByIdMutationVariablesAvo,
} from '~generated/graphql-db-types-avo';
import {
	DeleteContentBlockDocument as DeleteContentBlockDocumentHetArchief,
	DeleteContentBlockMutation as DeleteContentBlockMutationHetArchief,
	DeleteContentBlockMutationVariables as DeleteContentBlockMutationVariablesHetArchief,
	DeleteContentLabelLinksDocument as DeleteContentLabelLinksDocumentHetArchief,
	DeleteContentLabelLinksMutation as DeleteContentLabelLinksMutationHetArchief,
	DeleteContentLabelLinksMutationVariables as DeleteContentLabelLinksMutationVariablesHetArchief,
	GetContentByIdDocument as GetContentByIdDocumentHetArchief,
	GetContentByIdQuery as GetContentByIdQueryHetArchief,
	GetContentByIdQueryVariables as GetContentByIdQueryVariablesHetArchief,
	GetContentLabelsByContentTypeDocument as GetContentLabelsByContentTypeDocumentHetArchief,
	GetContentLabelsByContentTypeQuery as GetContentLabelsByContentTypeQueryHetArchief,
	GetContentLabelsByContentTypeQueryVariables as GetContentLabelsByContentTypeQueryVariablesHetArchief,
	GetContentPagesDocument as GetContentPagesDocumentHetArchief,
	GetContentPagesQuery as GetContentPagesQueryHetArchief,
	GetContentPagesQueryVariables as GetContentPagesQueryVariablesHetArchief,
	GetContentTypesDocument as GetContentTypesDocumentHetArchief,
	GetContentTypesQuery as GetContentTypesQueryHetArchief,
	GetContentTypesQueryVariables as GetContentTypesQueryVariablesHetArchief,
	GetPermissionsFromContentPageByPathDocument as GetPermissionsFromContentPageByPathDocumentHetArchief,
	GetPermissionsFromContentPageByPathQuery as GetPermissionsFromContentPageByPathQueryHetArchief,
	GetPermissionsFromContentPageByPathQueryVariables as GetPermissionsFromContentPageByPathQueryVariablesHetArchief,
	GetPublicContentPagesByTitleDocument as GetPublicContentPagesByTitleDocumentHetArchief,
	GetPublicContentPagesByTitleQuery as GetPublicContentPagesByTitleQueryHetArchief,
	GetPublicContentPagesByTitleQueryVariables as GetPublicContentPagesByTitleQueryVariablesHetArchief,
	GetPublicProjectContentPagesByTitleDocument as GetPublicProjectContentPagesByTitleDocumentHetArchief,
	GetPublicProjectContentPagesByTitleQuery as GetPublicProjectContentPagesByTitleQueryHetArchief,
	GetPublicProjectContentPagesByTitleQueryVariables as GetPublicProjectContentPagesByTitleQueryVariablesHetArchief,
	GetPublicProjectContentPagesDocument as GetPublicProjectContentPagesDocumentHetArchief,
	GetPublicProjectContentPagesQuery as GetPublicProjectContentPagesQueryHetArchief,
	GetPublicProjectContentPagesQueryVariables as GetPublicProjectContentPagesQueryVariablesHetArchief,
	InsertContentBlocksDocument as InsertContentBlocksDocumentHetArchief,
	InsertContentBlocksMutation as InsertContentBlocksMutationHetArchief,
	InsertContentBlocksMutationVariables as InsertContentBlocksMutationVariablesHetArchief,
	InsertContentDocument as InsertContentDocumentHetArchief,
	InsertContentLabelLinksDocument as InsertContentLabelLinksDocumentHetArchief,
	InsertContentLabelLinksMutation as InsertContentLabelLinksMutationHetArchief,
	InsertContentLabelLinksMutationVariables as InsertContentLabelLinksMutationVariablesHetArchief,
	InsertContentMutation as InsertContentMutationHetArchief,
	InsertContentMutationVariables as InsertContentMutationVariablesHetArchief,
	SoftDeleteContentDocument as SoftDeleteContentDocumentHetArchief,
	SoftDeleteContentMutation as SoftDeleteContentMutationHetArchief,
	SoftDeleteContentMutationVariables as SoftDeleteContentMutationVariablesHetArchief,
	UpdateContentBlockDocument as UpdateContentBlockDocumentHetArchief,
	UpdateContentBlockMutation as UpdateContentBlockMutationHetArchief,
	UpdateContentBlockMutationVariables as UpdateContentBlockMutationVariablesHetArchief,
	UpdateContentByIdDocument as UpdateContentByIdDocumentHetArchief,
	UpdateContentByIdMutation as UpdateContentByIdMutationHetArchief,
	UpdateContentByIdMutationVariables as UpdateContentByIdMutationVariablesHetArchief,
} from '~generated/graphql-db-types-hetarchief';

export type ContentPageQueryTypes = {
	GetContentByIdQuery: GetContentByIdQueryAvo | GetContentByIdQueryHetArchief;
	GetContentByIdQueryHetArchief: GetContentByIdQueryHetArchief;
	GetContentByIdQueryAvo: GetContentByIdQueryAvo;
	GetContentLabelsByContentTypeQueryAvo: GetContentLabelsByContentTypeQueryAvo;
	GetContentLabelsByContentTypeQueryHetArchief: GetContentLabelsByContentTypeQueryHetArchief;
	GetContentLabelsByContentTypeQuery:
		| GetContentLabelsByContentTypeQueryAvo
		| GetContentLabelsByContentTypeQueryHetArchief;
	GetContentPagesQueryAvo: GetContentPagesQueryAvo;
	GetContentPagesQueryHetArchief: GetContentPagesQueryHetArchief;
	GetContentPagesQuery: GetContentPagesQueryAvo | GetContentPagesQueryHetArchief;
	GetContentTypesQueryAvo: GetContentTypesQueryAvo;
	GetContentTypesQueryHetArchief: GetContentTypesQueryHetArchief;
	GetContentTypesQuery: GetContentTypesQueryAvo | GetContentTypesQueryHetArchief;
	GetPermissionsFromContentPageByPathQueryAvo: GetPermissionsFromContentPageByPathQueryAvo;
	GetPermissionsFromContentPageByPathQueryHetArchief: GetPermissionsFromContentPageByPathQueryHetArchief;
	GetPermissionsFromContentPageByPathQuery:
		| GetPermissionsFromContentPageByPathQueryAvo
		| GetPermissionsFromContentPageByPathQueryHetArchief;
	GetPublicContentPagesByTitleQueryAvo: GetPublicContentPagesByTitleQueryAvo;
	GetPublicContentPagesByTitleQueryHetArchief: GetPublicContentPagesByTitleQueryHetArchief;
	GetPublicContentPagesByTitleQuery:
		| GetPublicContentPagesByTitleQueryAvo
		| GetPublicContentPagesByTitleQueryHetArchief;
	GetPublicProjectContentPagesByTitleQueryAvo: GetPublicProjectContentPagesByTitleQueryAvo;
	GetPublicProjectContentPagesByTitleQueryHetArchief: GetPublicProjectContentPagesByTitleQueryHetArchief;
	GetPublicProjectContentPagesByTitleQuery:
		| GetPublicProjectContentPagesByTitleQueryAvo
		| GetPublicProjectContentPagesByTitleQueryHetArchief;
	GetPublicProjectContentPagesQueryAvo: GetPublicProjectContentPagesQueryAvo;
	GetPublicProjectContentPagesQueryHetArchief: GetPublicProjectContentPagesQueryHetArchief;
	GetPublicProjectContentPagesQuery:
		| GetPublicProjectContentPagesQueryAvo
		| GetPublicProjectContentPagesQueryHetArchief;
	GetContentByIdQueryVariablesAvo: GetContentByIdQueryVariablesAvo;
	GetContentByIdQueryVariablesHetArchief: GetContentByIdQueryVariablesHetArchief;
	GetContentByIdQueryVariables:
		| GetContentByIdQueryVariablesAvo
		| GetContentByIdQueryVariablesHetArchief;
	GetContentLabelsByContentTypeQueryVariablesAvo: GetContentLabelsByContentTypeQueryVariablesAvo;
	GetContentLabelsByContentTypeQueryVariablesHetArchief: GetContentLabelsByContentTypeQueryVariablesHetArchief;
	GetContentLabelsByContentTypeQueryVariables:
		| GetContentLabelsByContentTypeQueryVariablesAvo
		| GetContentLabelsByContentTypeQueryVariablesHetArchief;
	GetContentPagesQueryVariablesAvo: GetContentPagesQueryVariablesAvo;
	GetContentPagesQueryVariablesHetArchief: GetContentPagesQueryVariablesHetArchief;
	GetContentPagesQueryVariables:
		| GetContentPagesQueryVariablesAvo
		| GetContentPagesQueryVariablesHetArchief;
	GetContentTypesQueryVariablesAvo: GetContentTypesQueryVariablesAvo;
	GetContentTypesQueryVariablesHetArchief: GetContentTypesQueryVariablesHetArchief;
	GetContentTypesQueryVariables:
		| GetContentTypesQueryVariablesAvo
		| GetContentTypesQueryVariablesHetArchief;
	GetPermissionsFromContentPageByPathQueryVariablesAvo: GetPermissionsFromContentPageByPathQueryVariablesAvo;
	GetPermissionsFromContentPageByPathQueryVariablesHetArchief: GetPermissionsFromContentPageByPathQueryVariablesHetArchief;
	GetPermissionsFromContentPageByPathQueryVariables:
		| GetPermissionsFromContentPageByPathQueryVariablesAvo
		| GetPermissionsFromContentPageByPathQueryVariablesHetArchief;
	GetPublicContentPagesByTitleQueryVariablesAvo: GetPublicContentPagesByTitleQueryVariablesAvo;
	GetPublicContentPagesByTitleQueryVariablesHetArchief: GetPublicContentPagesByTitleQueryVariablesHetArchief;
	GetPublicContentPagesByTitleQueryVariables:
		| GetPublicContentPagesByTitleQueryVariablesAvo
		| GetPublicContentPagesByTitleQueryVariablesHetArchief;
	GetPublicProjectContentPagesByTitleQueryVariablesAvo: GetPublicProjectContentPagesByTitleQueryVariablesAvo;
	GetPublicProjectContentPagesByTitleQueryVariablesHetArchief: GetPublicProjectContentPagesByTitleQueryVariablesHetArchief;
	GetPublicProjectContentPagesByTitleQueryVariables:
		| GetPublicProjectContentPagesByTitleQueryVariablesAvo
		| GetPublicProjectContentPagesByTitleQueryVariablesHetArchief;
	GetPublicProjectContentPagesQueryVariablesAvo: GetPublicProjectContentPagesQueryVariablesAvo;
	GetPublicProjectContentPagesQueryVariablesHetArchief: GetPublicProjectContentPagesQueryVariablesHetArchief;
	GetPublicProjectContentPagesQueryVariables:
		| GetPublicProjectContentPagesQueryVariablesAvo
		| GetPublicProjectContentPagesQueryVariablesHetArchief;
	DeleteContentBlockMutationAvo: DeleteContentBlockMutationAvo;
	DeleteContentBlockMutationHetArchief: DeleteContentBlockMutationHetArchief;
	DeleteContentBlockMutation:
		| DeleteContentBlockMutationAvo
		| DeleteContentBlockMutationHetArchief;
	DeleteContentLabelLinksMutationAvo: DeleteContentLabelLinksMutationAvo;
	DeleteContentLabelLinksMutationHetArchief: DeleteContentLabelLinksMutationHetArchief;
	DeleteContentLabelLinksMutation:
		| DeleteContentLabelLinksMutationAvo
		| DeleteContentLabelLinksMutationHetArchief;
	InsertContentBlocksMutationAvo: InsertContentBlocksMutationAvo;
	InsertContentBlocksMutationHetArchief: InsertContentBlocksMutationHetArchief;
	InsertContentBlocksMutation:
		| InsertContentBlocksMutationAvo
		| InsertContentBlocksMutationHetArchief;
	InsertContentMutationAvo: InsertContentMutationAvo;
	InsertContentMutationHetArchief: InsertContentMutationHetArchief;
	InsertContentMutation: InsertContentMutationAvo | InsertContentMutationHetArchief;
	InsertContentLabelLinksMutationAvo: InsertContentLabelLinksMutationAvo;
	InsertContentLabelLinksMutationHetArchief: InsertContentLabelLinksMutationHetArchief;
	InsertContentLabelLinksMutation:
		| InsertContentLabelLinksMutationAvo
		| InsertContentLabelLinksMutationHetArchief;
	SoftDeleteContentMutationAvo: SoftDeleteContentMutationAvo;
	SoftDeleteContentMutationHetArchief: SoftDeleteContentMutationHetArchief;
	SoftDeleteContentMutation: SoftDeleteContentMutationAvo | SoftDeleteContentMutationHetArchief;
	UpdateContentBlockMutationAvo: UpdateContentBlockMutationAvo;
	UpdateContentBlockMutationHetArchief: UpdateContentBlockMutationHetArchief;
	UpdateContentBlockMutation:
		| UpdateContentBlockMutationAvo
		| UpdateContentBlockMutationHetArchief;
	UpdateContentByIdMutationAvo: UpdateContentByIdMutationAvo;
	UpdateContentByIdMutationHetArchief: UpdateContentByIdMutationHetArchief;
	UpdateContentByIdMutation: UpdateContentByIdMutationAvo | UpdateContentByIdMutationHetArchief;
	DeleteContentBlockMutationVariablesAvo: DeleteContentBlockMutationVariablesAvo;
	DeleteContentBlockMutationVariablesHetArchief: DeleteContentBlockMutationVariablesHetArchief;
	DeleteContentBlockMutationVariables:
		| DeleteContentBlockMutationVariablesAvo
		| DeleteContentBlockMutationVariablesHetArchief;
	DeleteContentLabelLinksMutationVariablesAvo: DeleteContentLabelLinksMutationVariablesAvo;
	DeleteContentLabelLinksMutationVariablesHetArchief: DeleteContentLabelLinksMutationVariablesHetArchief;
	DeleteContentLabelLinksMutationVariables:
		| DeleteContentLabelLinksMutationVariablesAvo
		| DeleteContentLabelLinksMutationVariablesHetArchief;
	InsertContentBlocksMutationVariablesAvo: InsertContentBlocksMutationVariablesAvo;
	InsertContentBlocksMutationVariablesHetArchief: InsertContentBlocksMutationVariablesHetArchief;
	InsertContentBlocksMutationVariables:
		| InsertContentBlocksMutationVariablesAvo
		| InsertContentBlocksMutationVariablesHetArchief;
	InsertContentMutationVariablesAvo: InsertContentMutationVariablesAvo;
	InsertContentMutationVariablesHetArchief: InsertContentMutationVariablesHetArchief;
	InsertContentMutationVariables:
		| InsertContentMutationVariablesAvo
		| InsertContentMutationVariablesHetArchief;
	InsertContentLabelLinksMutationVariablesAvo: InsertContentLabelLinksMutationVariablesAvo;
	InsertContentLabelLinksMutationVariablesHetArchief: InsertContentLabelLinksMutationVariablesHetArchief;
	InsertContentLabelLinksMutationVariables:
		| InsertContentLabelLinksMutationVariablesAvo
		| InsertContentLabelLinksMutationVariablesHetArchief;
	SoftDeleteContentMutationVariablesAvo: SoftDeleteContentMutationVariablesAvo;
	SoftDeleteContentMutationVariablesHetArchief: SoftDeleteContentMutationVariablesHetArchief;
	SoftDeleteContentMutationVariables:
		| SoftDeleteContentMutationVariablesAvo
		| SoftDeleteContentMutationVariablesHetArchief;
	UpdateContentBlockMutationVariablesAvo: UpdateContentBlockMutationVariablesAvo;
	UpdateContentBlockMutationVariablesHetArchief: UpdateContentBlockMutationVariablesHetArchief;
	UpdateContentBlockMutationVariables:
		| UpdateContentBlockMutationVariablesAvo
		| UpdateContentBlockMutationVariablesHetArchief;
	UpdateContentByIdMutationVariablesAvo: UpdateContentByIdMutationVariablesAvo;
	UpdateContentByIdMutationVariablesHetArchief: UpdateContentByIdMutationVariablesHetArchief;
	UpdateContentByIdMutationVariables:
		| UpdateContentByIdMutationVariablesAvo
		| UpdateContentByIdMutationVariablesHetArchief;
};

type ContentPageQueries = {
	DeleteContentBlockDocument: string;
	DeleteContentLabelLinksDocument: string;
	GetContentByIdDocument: string;
	GetContentLabelsByContentTypeDocument: string;
	GetContentPagesDocument: string;
	GetContentTypesDocument: string;
	GetPermissionsFromContentPageByPathDocument: string;
	GetPublicContentPagesByTitleDocument: string;
	GetPublicProjectContentPagesByTitleDocument: string;
	GetPublicProjectContentPagesDocument: string;
	InsertContentBlocksDocument: string;
	InsertContentDocument: string;
	InsertContentLabelLinksDocument: string;
	SoftDeleteContentDocument: string;
	UpdateContentBlockDocument: string;
	UpdateContentByIdDocument: string;
};

export const CONTENT_PAGE_QUERIES: Record<AvoOrHetArchief, ContentPageQueries> = {
	[AvoOrHetArchief.avo]: {
		DeleteContentBlockDocument: DeleteContentBlockDocumentAvo,
		DeleteContentLabelLinksDocument: DeleteContentLabelLinksDocumentAvo,
		GetContentByIdDocument: GetContentByIdDocumentAvo,
		GetContentLabelsByContentTypeDocument: GetContentLabelsByContentTypeDocumentAvo,
		GetContentPagesDocument: GetContentPagesDocumentAvo,
		GetContentTypesDocument: GetContentTypesDocumentAvo,
		GetPermissionsFromContentPageByPathDocument: GetPermissionsFromContentPageByPathDocumentAvo,
		GetPublicContentPagesByTitleDocument: GetPublicContentPagesByTitleDocumentAvo,
		GetPublicProjectContentPagesByTitleDocument: GetPublicProjectContentPagesByTitleDocumentAvo,
		GetPublicProjectContentPagesDocument: GetPublicProjectContentPagesDocumentAvo,
		InsertContentBlocksDocument: InsertContentBlocksDocumentAvo,
		InsertContentDocument: InsertContentDocumentAvo,
		InsertContentLabelLinksDocument: InsertContentLabelLinksDocumentAvo,
		SoftDeleteContentDocument: SoftDeleteContentDocumentAvo,
		UpdateContentBlockDocument: UpdateContentBlockDocumentAvo,
		UpdateContentByIdDocument: UpdateContentByIdDocumentAvo,
	},
	[AvoOrHetArchief.hetArchief]: {
		DeleteContentBlockDocument: DeleteContentBlockDocumentHetArchief,
		DeleteContentLabelLinksDocument: DeleteContentLabelLinksDocumentHetArchief,
		GetContentByIdDocument: GetContentByIdDocumentHetArchief,
		GetContentLabelsByContentTypeDocument: GetContentLabelsByContentTypeDocumentHetArchief,
		GetContentPagesDocument: GetContentPagesDocumentHetArchief,
		GetContentTypesDocument: GetContentTypesDocumentHetArchief,
		GetPermissionsFromContentPageByPathDocument:
			GetPermissionsFromContentPageByPathDocumentHetArchief,
		GetPublicContentPagesByTitleDocument: GetPublicContentPagesByTitleDocumentHetArchief,
		GetPublicProjectContentPagesByTitleDocument:
			GetPublicProjectContentPagesByTitleDocumentHetArchief,
		GetPublicProjectContentPagesDocument: GetPublicProjectContentPagesDocumentHetArchief,
		InsertContentBlocksDocument: InsertContentBlocksDocumentHetArchief,
		InsertContentDocument: InsertContentDocumentHetArchief,
		InsertContentLabelLinksDocument: InsertContentLabelLinksDocumentHetArchief,
		SoftDeleteContentDocument: SoftDeleteContentDocumentHetArchief,
		UpdateContentBlockDocument: UpdateContentBlockDocumentHetArchief,
		UpdateContentByIdDocument: UpdateContentByIdDocumentHetArchief,
	},
};
