import { PermissionName } from '@viaa/avo2-types';

import { Avo } from '@viaa/avo2-types';

export const mockUser: Avo.User.CommonUser = {
	uid: '02ceadae-a1c5-4fe4-a503-c5b0e7fb9922',
	profileId: '31051baa-94ab-4fc2-a859-750a52774d3a',
	userId: '02ceadae-a1c5-4fe4-a503-c5b0e7fb9922',
	email: 'hetarchief2.0+bztmeemooadmin@meemoo.be',
	acceptedTosAt: '1970-01-01',
	userGroup: {
		name: '1',
		id: 1,
	},
	firstName: 'meemoo',
	lastName: 'Admin',
	fullName: 'meemoo Admin',
	lastAccessAt: '2023-02-06T20:05:53.243+00:00',
	permissions: [
		PermissionName.ADD_COLLECTION_TO_BUNDLE_BY_ID,
		PermissionName.ADD_HYPERLINK_COLLECTIONS,
		PermissionName.ADD_ITEM_TO_COLLECTION_BY_PID,
		PermissionName.AUTOPLAY_COLLECTION,
		PermissionName.CREATE_ASSIGNMENTS,
		PermissionName.CREATE_BOOKMARKS,
		PermissionName.CREATE_BUNDLES,
		PermissionName.CREATE_COLLECTIONS,
		PermissionName.CREATE_CONTENT_PAGES,
		PermissionName.CREATE_QUICK_LANE,
		PermissionName.DELETE_ANY_ASSIGNMENTS,
		PermissionName.DELETE_ANY_BUNDLES,
		PermissionName.DELETE_ANY_COLLECTIONS,
		PermissionName.DELETE_ANY_CONTENT_PAGES,
		PermissionName.DELETE_ANY_PUPIL_COLLECTIONS,
		PermissionName.DELETE_ANY_USER,
		PermissionName.DELETE_OWN_BUNDLES,
		PermissionName.DELETE_OWN_COLLECTIONS,
		PermissionName.EDIT_ANY_ASSIGNMENTS,
		PermissionName.EDIT_ANY_ASSIGNMENT_RESPONSES,
		PermissionName.EDIT_ANY_BUNDLES,
		PermissionName.EDIT_ANY_COLLECTIONS,
		PermissionName.EDIT_ANY_CONTENT_PAGES,
		PermissionName.EDIT_ANY_PUPIL_COLLECTIONS,
		PermissionName.EDIT_ANY_USER,
		PermissionName.EDIT_BAN_USER_STATUS,
		PermissionName.EDIT_BUNDLE_AUTHOR,
		PermissionName.EDIT_BUNDLE_EDITORIAL_STATUS,
		PermissionName.EDIT_BUNDLE_LABELS,
		PermissionName.EDIT_COLLECTION_AUTHOR,
		PermissionName.EDIT_COLLECTION_EDITORIAL_STATUS,
		PermissionName.EDIT_COLLECTION_LABELS,
		PermissionName.EDIT_CONTENT_PAGE_AUTHOR,
		PermissionName.EDIT_CONTENT_PAGE_LABELS,
		PermissionName.EDIT_EDUCATIONAL_ORGANISATION_ON_PROFILE_PAGE,
		PermissionName.EDIT_EDUCATION_LEVEL_ON_PROFILE_PAGE,
		PermissionName.EDIT_INTERACTIVE_TOURS,
		PermissionName.EDIT_NAVIGATION_BARS,
		PermissionName.EDIT_ORGANISATION_ON_PROFILE_PAGE,
		PermissionName.EDIT_OWN_ASSIGNMENTS,
		PermissionName.EDIT_OWN_BUNDLES,
		PermissionName.EDIT_OWN_COLLECTIONS,
		PermissionName.EDIT_OWN_CONTENT_PAGES,
		PermissionName.EDIT_OWN_QUICK_LANE,
		PermissionName.EDIT_PROTECTED_PAGE_STATUS,
		PermissionName.EDIT_SUBJECTS_ON_PROFILE_PAGE,
		PermissionName.EDIT_TRANSLATIONS,
		PermissionName.EDIT_USER_GROUPS,
		PermissionName.EDIT_USER_TEMP_ACCESS,
		PermissionName.PUBLISH_ANY_BUNDLES,
		PermissionName.PUBLISH_ANY_COLLECTIONS,
		PermissionName.PUBLISH_ANY_CONTENT_PAGE,
		PermissionName.PUBLISH_ITEMS,
		PermissionName.PUBLISH_OWN_BUNDLES,
		PermissionName.PUBLISH_OWN_COLLECTIONS,
		PermissionName.REQUIRED_ORGANISATION_ON_PROFILE_PAGE,
		PermissionName.REQUIRED_PUBLICATION_DETAILS_ON_QUICK_LANE,
		PermissionName.SEARCH,
		PermissionName.SEARCH_IN_ASSIGNMENT,
		PermissionName.UNPUBLISH_ANY_CONTENT_PAGE,
		PermissionName.VIEW_ADMIN_DASHBOARD,
		PermissionName.VIEW_ANY_ASSIGNMENTS,
		PermissionName.VIEW_ANY_ASSIGNMENT_RESPONSES,
		PermissionName.VIEW_ANY_PUBLISHED_BUNDLES,
		PermissionName.VIEW_ANY_PUBLISHED_COLLECTIONS,
		PermissionName.VIEW_ANY_PUBLISHED_ITEMS,
		PermissionName.VIEW_ANY_PUPIL_COLLECTIONS,
		PermissionName.VIEW_ANY_QUICK_LANE_OVERVIEW,
		PermissionName.VIEW_ANY_UNPUBLISHED_BUNDLES,
		PermissionName.VIEW_ANY_UNPUBLISHED_COLLECTIONS,
		PermissionName.VIEW_ANY_UNPUBLISHED_ITEMS,
		PermissionName.VIEW_ASSIGNMENTS,
		PermissionName.VIEW_ASSOCIATED_QUICK_LANE,
		PermissionName.VIEW_BUNDLES_OVERVIEW,
		PermissionName.VIEW_BUNDLE_EDITORIAL_OVERVIEWS,
		PermissionName.VIEW_COLLECTIONS_OVERVIEW,
		PermissionName.VIEW_COLLECTION_EDITORIAL_OVERVIEWS,
		PermissionName.VIEW_EDUCATIONAL_ORGANISATION_ON_PROFILE_PAGE,
		PermissionName.VIEW_EDUCATION_LEVEL_ON_PROFILE_PAGE,
		PermissionName.VIEW_ITEMS_OVERVIEW,
		PermissionName.VIEW_NEWSLETTERS_PAGE,
		PermissionName.VIEW_ORGANISATION_ON_PROFILE_PAGE,
		PermissionName.VIEW_OWN_ASSIGNMENT_RESPONSES,
		PermissionName.VIEW_OWN_BUNDLES,
		PermissionName.VIEW_OWN_COLLECTIONS,
		PermissionName.VIEW_PERSONAL_QUICK_LANE_OVERVIEW,
		PermissionName.VIEW_QUICK_LANE_DETAIL,
		PermissionName.VIEW_SUBJECTS_ON_PROFILE_PAGE,
		PermissionName.VIEW_USERS,
	],
	tempAccess: undefined,
};
