import { AvoOrHetArchief } from '../../shared/types';

import {
	DeleteUserGroupDocument as DeleteUserGroupDocumentAvo,
	DeleteUserGroupMutation as DeleteUserGroupMutationAvo,
	DeleteUserGroupMutationVariables as DeleteUserGroupMutationVariablesAvo,
	GetUserGroupByIdDocument as GetUserGroupByIdDocumentAvo,
	GetUserGroupByIdQuery as GetUserGroupByIdQueryAvo,
	GetUserGroupByIdQueryVariables as GetUserGroupByIdQueryVariablesAvo,
	GetUserGroupsWithFiltersDocument as GetUserGroupsWithFiltersDocumentAvo,
	GetUserGroupsWithFiltersQuery as GetUserGroupsWithFiltersQueryAvo,
	GetUserGroupsWithFiltersQueryVariables as GetUserGroupsWithFiltersQueryVariablesAvo,
	InsertUserGroupDocument as InsertUserGroupDocumentAvo,
	InsertUserGroupMutation as InsertUserGroupMutationAvo,
	InsertUserGroupMutationVariables as InsertUserGroupMutationVariablesAvo,
	UpdateUserGroupDocument as UpdateUserGroupDocumentAvo,
	UpdateUserGroupMutation as UpdateUserGroupMutationAvo,
	UpdateUserGroupMutationVariables as UpdateUserGroupMutationVariablesAvo,
} from '~generated/graphql-db-types-avo';
import {
	DeleteUserGroupDocument as DeleteUserGroupDocumentHetArchief,
	DeleteUserGroupMutation as DeleteUserGroupMutationHetArchief,
	DeleteUserGroupMutationVariables as DeleteUserGroupMutationVariablesHetArchief,
	GetUserGroupByIdDocument as GetUserGroupByIdDocumentHetArchief,
	GetUserGroupByIdQuery as GetUserGroupByIdQueryHetArchief,
	GetUserGroupByIdQueryVariables as GetUserGroupByIdQueryVariablesHetArchief,
	GetUserGroupsWithFiltersDocument as GetUserGroupsWithFiltersDocumentHetArchief,
	GetUserGroupsWithFiltersQuery as GetUserGroupsWithFiltersQueryHetArchief,
	GetUserGroupsWithFiltersQueryVariables as GetUserGroupsWithFiltersQueryVariablesHetArchief,
	InsertUserGroupDocument as InsertUserGroupDocumentHetArchief,
	InsertUserGroupMutation as InsertUserGroupMutationHetArchief,
	InsertUserGroupMutationVariables as InsertUserGroupMutationVariablesHetArchief,
	UpdateUserGroupDocument as UpdateUserGroupDocumentHetArchief,
	UpdateUserGroupMutation as UpdateUserGroupMutationHetArchief,
	UpdateUserGroupMutationVariables as UpdateUserGroupMutationVariablesHetArchief,
} from '~generated/graphql-db-types-hetarchief';

export type UserGroupQueryTypes = {
	GetUserGroupByIdQueryVariables:
		| GetUserGroupByIdQueryVariablesAvo
		| GetUserGroupByIdQueryVariablesHetArchief;
	GetUserGroupByIdQuery: GetUserGroupByIdQueryAvo | GetUserGroupByIdQueryHetArchief;
	GetUserGroupByIdQueryVariablesAvo: GetUserGroupByIdQueryVariablesAvo;
	GetUserGroupByIdQueryAvo: GetUserGroupByIdQueryAvo;
	GetUserGroupByIdQueryVariablesHetArchief: GetUserGroupByIdQueryVariablesHetArchief;
	GetUserGroupByIdQueryHetArchief: GetUserGroupByIdQueryHetArchief;
	GetUserGroupsWithFiltersQueryVariables:
		| GetUserGroupsWithFiltersQueryVariablesAvo
		| GetUserGroupsWithFiltersQueryVariablesHetArchief;
	GetUserGroupsWithFiltersQuery:
		| GetUserGroupsWithFiltersQueryAvo
		| GetUserGroupsWithFiltersQueryHetArchief;
	GetUserGroupsWithFiltersQueryVariablesAvo: GetUserGroupsWithFiltersQueryVariablesAvo;
	GetUserGroupsWithFiltersQueryAvo: GetUserGroupsWithFiltersQueryAvo;
	GetUserGroupsWithFiltersQueryVariablesHetArchief: GetUserGroupsWithFiltersQueryVariablesHetArchief;
	GetUserGroupsWithFiltersQueryHetArchief: GetUserGroupsWithFiltersQueryHetArchief;
	InsertUserGroupMutationVariables:
		| InsertUserGroupMutationVariablesAvo
		| InsertUserGroupMutationVariablesHetArchief;
	InsertUserGroupMutation: InsertUserGroupMutationAvo | InsertUserGroupMutationHetArchief;
	InsertUserGroupMutationVariablesAvo: InsertUserGroupMutationVariablesAvo;
	InsertUserGroupMutationAvo: InsertUserGroupMutationAvo;
	InsertUserGroupMutationVariablesHetArchief: InsertUserGroupMutationVariablesHetArchief;
	InsertUserGroupMutationHetArchief: InsertUserGroupMutationHetArchief;
	UpdateUserGroupMutationVariables:
		| UpdateUserGroupMutationVariablesAvo
		| UpdateUserGroupMutationVariablesHetArchief;
	UpdateUserGroupMutation: UpdateUserGroupMutationAvo | UpdateUserGroupMutationHetArchief;
	UpdateUserGroupMutationVariablesAvo: UpdateUserGroupMutationVariablesAvo;
	UpdateUserGroupMutationAvo: UpdateUserGroupMutationAvo;
	UpdateUserGroupMutationVariablesHetArchief: UpdateUserGroupMutationVariablesHetArchief;
	UpdateUserGroupMutationHetArchief: UpdateUserGroupMutationHetArchief;
	DeleteUserGroupMutationVariables:
		| DeleteUserGroupMutationVariablesAvo
		| DeleteUserGroupMutationVariablesHetArchief;
	DeleteUserGroupMutation: DeleteUserGroupMutationAvo | DeleteUserGroupMutationHetArchief;
	DeleteUserGroupMutationVariablesAvo: DeleteUserGroupMutationVariablesAvo;
	DeleteUserGroupMutationAvo: DeleteUserGroupMutationAvo;
	DeleteUserGroupMutationVariablesHetArchief: DeleteUserGroupMutationVariablesHetArchief;
	DeleteUserGroupMutationHetArchief: DeleteUserGroupMutationHetArchief;
};

interface UserGroupQueries {
	GetUserGroupByIdDocument: string;
	GetUserGroupsWithFiltersDocument: string;
	InsertUserGroupDocument: string;
	UpdateUserGroupDocument: string;
	DeleteUserGroupDocument: string;
}

export const USER_GROUP_QUERIES: Record<AvoOrHetArchief, UserGroupQueries> = {
	[AvoOrHetArchief.avo]: {
		GetUserGroupsWithFiltersDocument: GetUserGroupsWithFiltersDocumentAvo,
		GetUserGroupByIdDocument: GetUserGroupByIdDocumentAvo,
		InsertUserGroupDocument: InsertUserGroupDocumentAvo,
		UpdateUserGroupDocument: UpdateUserGroupDocumentAvo,
		DeleteUserGroupDocument: DeleteUserGroupDocumentAvo,
	},
	[AvoOrHetArchief.hetArchief]: {
		GetUserGroupsWithFiltersDocument: GetUserGroupsWithFiltersDocumentHetArchief,
		GetUserGroupByIdDocument: GetUserGroupByIdDocumentHetArchief,
		InsertUserGroupDocument: InsertUserGroupDocumentHetArchief,
		UpdateUserGroupDocument: UpdateUserGroupDocumentHetArchief,
		DeleteUserGroupDocument: DeleteUserGroupDocumentHetArchief,
	},
};
