import { PermissionName } from '@viaa/avo2-types';

export const mockUserInfo = {
	first_name: 'Bert',
	last_name: 'Verhelst',
	temp_access: null,
	is_blocked: false,
	profile: {
		id: '69ccef3b-751a-4be4-95bc-5ef365fbd504',
		alias: 'bert_verhelst',
		title: 'Developer1',
		alternative_email: 'verhelstbert@gmail.comaaaaaaa',
		avatar:
			'https://assets-qas.hetarchief.be//avo2/PROFILE_AVATAR/bert-359813c0-3b43-11ed-937e-adfb7fd0632b.jpg',
		created_at: '2019-10-23T16:22:47.543339+00:00',
		stamboek: '',
		bio: 'Ik ben een developer bij Studio Hyperdrive',
		updated_at: '2022-11-28T08:23:35.658+00:00',
		user_id: '517aec71-cf0e-4e08-99d1-8e7e042923f7',
		is_exception: true,
		business_category: 'VDAB',
		company_id: 'OR-h41jm1d',
		organisation: {
			logo_url: 'https://assets-qas.viaa.be/images/OR-h41jm1d',
			name: 'meemoo - Het Archief voor Onderwijs',
			or_id: 'OR-h41jm1d',
		},
		userGroupIds: [1],
		permissions: [
			PermissionName.EDIT_EDUCATIONAL_ORGANISATION_ON_PROFILE_PAGE,
			PermissionName.EDIT_ORGANISATION_ON_PROFILE_PAGE,
			PermissionName.EDIT_CONTENT_PAGE_LABELS,
			PermissionName.EDIT_BAN_USER_STATUS,
			PermissionName.EDIT_PERMISSION_GROUPS,
			PermissionName.EDIT_USER_GROUPS,
			PermissionName.EDIT_NAVIGATION_BARS,
			PermissionName.EDIT_PROTECTED_PAGE_STATUS,
			PermissionName.VIEW_USERS,
			PermissionName.EDIT_TRANSLATIONS,
			PermissionName.DELETE_ANY_USER,
			PermissionName.EDIT_ANY_USER,
			PermissionName.EDIT_USER_TEMP_ACCESS,
			PermissionName.UNPUBLISH_ANY_CONTENT_PAGE,
			PermissionName.EDIT_INTERACTIVE_TOURS,
			PermissionName.DELETE_ANY_CONTENT_PAGES,
			PermissionName.PUBLISH_ITEMS,
			PermissionName.EDIT_BUNDLE_EDITORIAL_STATUS,
			PermissionName.EDIT_COLLECTION_EDITORIAL_STATUS,
			PermissionName.EDIT_ANY_ASSIGNMENTS,
			PermissionName.DELETE_ANY_ASSIGNMENTS,
			PermissionName.EDIT_ANY_ASSIGNMENT_RESPONSES,
			PermissionName.EDIT_ANY_PUPIL_COLLECTIONS,
			PermissionName.DELETE_ANY_PUPIL_COLLECTIONS,
			PermissionName.VIEW_ANY_UNPUBLISHED_COLLECTIONS,
			PermissionName.VIEW_ANY_UNPUBLISHED_BUNDLES,
			PermissionName.PUBLISH_ANY_CONTENT_PAGE,
			PermissionName.VIEW_ANY_UNPUBLISHED_ITEMS,
			PermissionName.CREATE_CONTENT_PAGES,
			PermissionName.EDIT_ANY_CONTENT_PAGES,
			PermissionName.VIEW_ITEMS_OVERVIEW,
			PermissionName.VIEW_COLLECTIONS_OVERVIEW,
			PermissionName.VIEW_BUNDLES_OVERVIEW,
			PermissionName.EDIT_ANY_BUNDLES,
			PermissionName.PUBLISH_ANY_BUNDLES,
			PermissionName.DELETE_ANY_BUNDLES,
			PermissionName.EDIT_ANY_COLLECTIONS,
			PermissionName.DELETE_ANY_COLLECTIONS,
			PermissionName.PUBLISH_ANY_COLLECTIONS,
			PermissionName.EDIT_COLLECTION_LABELS,
			PermissionName.EDIT_BUNDLE_LABELS,
			PermissionName.EDIT_COLLECTION_AUTHOR,
			PermissionName.EDIT_BUNDLE_AUTHOR,
			PermissionName.ADD_ITEM_TO_COLLECTION_BY_PID,
			PermissionName.ADD_COLLECTION_TO_BUNDLE_BY_ID,
			PermissionName.EDIT_CONTENT_PAGE_AUTHOR,
			PermissionName.VIEW_BUNDLE_EDITORIAL_OVERVIEWS,
			PermissionName.VIEW_COLLECTION_EDITORIAL_OVERVIEWS,
			PermissionName.VIEW_ASSOCIATED_QUICK_LANE,
			PermissionName.VIEW_ANY_QUICK_LANE_OVERVIEW,
			PermissionName.VIEW_ANY_PUPIL_COLLECTIONS,
			PermissionName.VIEW_ANY_ASSIGNMENTS,
			PermissionName.VIEW_ANY_ASSIGNMENT_RESPONSES,
			PermissionName.VIEW_ADMIN_DASHBOARD,
			PermissionName.EDIT_OWN_CONTENT_PAGES,
			PermissionName.PUBLISH_OWN_BUNDLES,
			PermissionName.EDIT_OWN_BUNDLES,
			PermissionName.CREATE_BUNDLES,
			PermissionName.ADD_HYPERLINK_COLLECTIONS,
			PermissionName.DELETE_OWN_BUNDLES,
			PermissionName.VIEW_OWN_BUNDLES,
			PermissionName.PUBLISH_OWN_COLLECTIONS,
			PermissionName.SEARCH,
			PermissionName.VIEW_OWN_COLLECTIONS,
			PermissionName.CREATE_BOOKMARKS,
			PermissionName.EDIT_OWN_COLLECTIONS,
			PermissionName.DELETE_OWN_COLLECTIONS,
			PermissionName.CREATE_COLLECTIONS,
			PermissionName.VIEW_ANY_PUBLISHED_COLLECTIONS,
			PermissionName.VIEW_ANY_PUBLISHED_ITEMS,
			PermissionName.VIEW_ANY_PUBLISHED_BUNDLES,
			PermissionName.VIEW_QUICK_LANE_DETAIL,
			PermissionName.AUTOPLAY_COLLECTION,
			PermissionName.CREATE_ASSIGNMENTS,
			PermissionName.VIEW_ASSIGNMENTS,
			PermissionName.SEARCH_IN_ASSIGNMENT,
			PermissionName.VIEW_OWN_ASSIGNMENT_RESPONSES,
			PermissionName.EDIT_OWN_ASSIGNMENTS,
			PermissionName.VIEW_EDUCATION_LEVEL_ON_PROFILE_PAGE,
			PermissionName.VIEW_SUBJECTS_ON_PROFILE_PAGE,
			PermissionName.EDIT_SUBJECTS_ON_PROFILE_PAGE,
			PermissionName.VIEW_NEWSLETTERS_PAGE,
			PermissionName.VIEW_ORGANISATION_ON_PROFILE_PAGE,
			PermissionName.REQUIRED_ORGANISATION_ON_PROFILE_PAGE,
			PermissionName.VIEW_EDUCATIONAL_ORGANISATION_ON_PROFILE_PAGE,
			PermissionName.EDIT_EDUCATION_LEVEL_ON_PROFILE_PAGE,
			PermissionName.CREATE_QUICK_LANE,
			PermissionName.EDIT_OWN_QUICK_LANE,
			PermissionName.VIEW_PERSONAL_QUICK_LANE_OVERVIEW,
			PermissionName.REQUIRED_PUBLICATION_DETAILS_ON_QUICK_LANE,
		],
		educationLevels: ['Deeltijds kunstonderwijs', 'Secundair onderwijs'],
		subjects: ['autotechniek', 'burgerzin'],
		organizations: [
			{ organizationId: 'OR-b853h7v', unitId: null, label: 'VDAB' },
		],
	},
	created_at: '2019-10-23T16:21:17.984884+00:00',
	expires_at: null,
	last_access_at: '2022-11-28T14:14:44.713+00:00',
	external_uid: null,
	role: { label: 'Beheerder', name: 'admin' },
	uid: '517aec71-cf0e-4e08-99d1-8e7e042923f7',
	updated_at: '2022-11-28T08:23:35.658+00:00',
	mail: 'bert.verhelst@studiohyperdrive.be',
	idpmaps: ['HETARCHIEF', 'KLASCEMENT', 'VLAAMSEOVERHEID__SUB_ID'],
	idpmapObjects: [
		{
			idp: 'HETARCHIEF',
			idp_user_id: '5eb99992-74a9-1039-9277-2bea2ee8ec01',
		},
		{
			idp: 'KLASCEMENT',
			idp_user_id: '5e7c68a6543c5',
		},
		{
			idp: 'VLAAMSEOVERHEID__SUB_ID',
			idp_user_id: '4d2b556cd6bffa86869507455afb0ee7329f41f2',
		},
	],
};
