export enum ContentPickerType {
	CONTENT_PAGE = 'CONTENT_PAGE',
	INTERNAL_LINK = 'INTERNAL_LINK',
	COLLECTION = 'COLLECTION',
	ITEM = 'ITEM',
	BUNDLE = 'BUNDLE',
	EXTERNAL_LINK = 'EXTERNAL_LINK',
	SEARCH_QUERY = 'SEARCH_QUERY',
	PROJECTS = 'PROJECTS',
	PROFILE = 'PROFILE',
	ANCHOR_LINK = 'ANCHOR_LINK',
	FILE = 'FILE',
}
