import { AvoAuthIdpType, type AvoUserHetArchiefUser, PermissionName } from '@viaa/avo2-types';

export const MOCK_HETARCHIEF_USER: AvoUserHetArchiefUser = {
	id: '31051baa-94ab-4fc2-a859-750a52774d3a',
	fullName: 'meemoo Admin',
	firstName: 'meemoo',
	lastName: 'Admin',
	email: 'hetarchief2.0+bztmeemooadmin@meemoo.be',
	language: 'nl',
	acceptedTosAt: '2023-03-31T14:30:25.086+02:00',
	groupId: '0b281484-76cd-45a9-b6ce-68a0ea7f4b26',
	groupName: 'MEEMOO_ADMIN',
	permissions: [
		PermissionName.APPROVE_DENY_ALL_VISIT_REQUESTS,
		PermissionName.CANCEL_OWN_VISIT_REQUEST,
		PermissionName.CREATE_CONTENT_PAGES,
		PermissionName.CREATE_MATERIAL_REQUESTS,
		PermissionName.CREATE_SPACES,
		PermissionName.CREATE_VISIT_REQUEST,
		PermissionName.DELETE_ANY_CONTENT_PAGES,
		PermissionName.DELETE_OWN_MATERIAL_REQUESTS,
		PermissionName.EDIT_ALL_SPACES_STATUS,
		PermissionName.EDIT_ANY_CONTENT_PAGES,
		PermissionName.EDIT_CONTENT_PAGE_AUTHOR,
		PermissionName.EDIT_CONTENT_PAGE_LABELS,
		PermissionName.EDIT_NAVIGATION_BARS,
		PermissionName.EDIT_OWN_MATERIAL_REQUESTS,
		PermissionName.EDIT_PERMISSION_GROUPS,
		PermissionName.EDIT_PROTECTED_PAGE_STATUS,
		PermissionName.EDIT_TRANSLATIONS,
		PermissionName.EDIT_USER_GROUPS,
		PermissionName.EXPORT_OBJECT,
		PermissionName.MANAGE_ACCOUNT,
		PermissionName.MANAGE_FOLDERS,
		PermissionName.PUBLISH_ANY_CONTENT_PAGE,
		PermissionName.READ_ALL_SPACES,
		PermissionName.READ_ALL_VISIT_REQUESTS,
		PermissionName.READ_PERSONAL_APPROVED_VISIT_REQUESTS,
		PermissionName.SEARCH_ALL_OBJECTS,
		PermissionName.SEARCH_OBJECTS,
		PermissionName.UNPUBLISH_ANY_CONTENT_PAGE,
		PermissionName.UPDATE_ALL_SPACES,
		PermissionName.VIEW_ADMIN_DASHBOARD,
		PermissionName.VIEW_ANY_MAINTENANCE_ALERTS,
		PermissionName.VIEW_ANY_MATERIAL_REQUESTS,
		PermissionName.VIEW_OWN_MATERIAL_REQUESTS,
		PermissionName.VIEW_USERS,
		PermissionName.CAN_EDIT_PROFILE_INFO,
	],
	idp: AvoAuthIdpType.HETARCHIEF, // Definitions of Idp enum in different repos cause typescript to be confused and not recognize them as the same type
	isKeyUser: false,
	isEvaluator: false,
	lastAccessAt: '2023-05-09T10:18:02.11+02:00',
	createdAt: '2023-01-30T16:26:38.875447',
	organisationName: 'meemoo',
	maintainerId: 'OR-w66976m',
	organisationId: 'OR-w66976m',
	sector: 'Cultuur',
};
